### PR TITLE
Initial work done on forcing cmod for RIP11, bug noted in comments

### PR DESCRIPTION
**Pull request by shoepickle**
Right now currently works if they go into the options menu and accidentally pick cmod, not for the case where they just pick a song. Noted unintentional behavior for now, mainly trying to find where it loads the options from if a song is picked only.

### CODE REVIEW

**Comment by ianklatzco** [comment]
@andrewipark we'll make a separate rip11 branch for this, most likely.

**Comment by andrewipark** [comment]
Alternatively, if you don't want to track that down, you could move the "force CMod" part of the code to gameplay init

**Comment by shoepickle** [comment]
Hi, updated it to not force cmod on players, instead just sending them back to the options screen. There's a bug with if a player has cmod and picks a no cmod song, it'll go to the options screen but then sound will stop playing. Am not sure how to get text to pop up properly for "Exit" without modifying the config file and having it always there, so players might be confused about why they're looping through the options screen. Any ideas?

**Comment by ianklatzco** [comment]
`but then sound will stop playing until in gameplay screen` This doesn't sound like a problem. Kinda disconcerting to players, tho.

`Am not sure how to get text to pop up properly for "Exit" without modifying the config file and having it always there, so players might be confused about why they're looping through the options screen.`

Can you clarify?

**Comment by shoepickle** [comment]
So if they never change cmod, it'll keep looping them back to options without telling them why (unless they go back to menu). I wanted the exit to change text from nothing to telling them to choose xmod/mmod or something like that, unless you tell everyone/show them expected behavior

**Comment by ianklatzco** [comment]
i see. it should be easy to hack text that conditionally says "no cmod allowed!!!" above the cmod indicator.

**Comment by ianklatzco** [comment]
yolo we need it hope it doesn't bug the fuck out of things. andrew, download a zip of rip11 branch, load it on all the cabs

**Comment by ianklatzco** [comment]
changing the displayname of the theme fucks w all the themeprefs.

**Comment by ianklatzco** [comment]
maybe just simply love options.

**Comment by shoepickle** [comment]
I'll look into it later, merge/use the other PR since I forgot I changed something in my testing that created a bad bug.

**Pull request merged**
